app: sykepengesoknad-narmesteleder-varsler
namespace: flex
team: flex
kafkaPool: nav-dev
db_tier: db-f1-micro
external-host:
  - pdl-api.dev-fss-pub.nais.io
azureTenant: trygdeetaten.no
env:
  PDL_BASE_URL: https://pdl-api.dev-fss-pub.nais.io
  PDL_API_AAD_CLIENT_ID: dev-fss.pdl.pdl-api
