app: sykepengesoknad-narmesteleder-varsler
namespace: flex
team: flex
kafkaPool: nav-prod
externalHosts:
  - pdl-api.prod-fss-pub.nais.io
azureTenant: nav.no
env:
  PDL_BASE_URL: https://pdl-api.prod-fss-pub.nais.io
  PDL_API_AAD_CLIENT_ID: prod-fss.pdl.pdl-api
