CREATE TABLE PLANLAGT_VARSEL
(
    ID                 VARCHAR(36) DEFAULT UUID_GENERATE_V4() PRIMARY KEY,
    OPPDATERT          TIMESTAMP WITH TIME ZONE NOT NULL,
    ORGNUMMER          VARCHAR                  NOT NULL,
    BRUKER_FNR         VARCHAR                  NOT NULL,
    SYKEPENGESOKNAD_ID VARCHAR                  NOT NULL,
    STATUS             VARCHAR                  NOT NULL,
    VARSEL_TYPE        VARCHAR                  NOT NULL,
    SENDES             TIMESTAMP WITH TIME ZONE NOT NULL
);


CREATE INDEX SYKEPENGESOKNAD_ID_IDX ON PLANLAGT_VARSEL (SYKEPENGESOKNAD_ID);
